# Global context
[build]
  # Base directory
  base = "docs"
  # Build command
  command = "yarn generate"
  # Build directory
  publish = "dist/"
  # Serverless Lambda functions
  functions = "lambda/"
  # Ignore builds
  ignore  = "git diff --quiet HEAD^ HEAD . ../package.json"

# Enforce yarn
[build.environment]
  NETLIFY_USE_YARN = "true"

# Post processing configuration
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.images]
  compress = true

# Deploy from production branch
[context.production]

[context.production.processing]
  skip_processing = false

# Deploy from pull and merge request
[context.deploy-preview]

[context.deploy-preview.processing]
  skip_processing = true

# Deploy from non production branches
[context.branch-deploy]

[context.branch-deploy.processing]
  skip_processing = true

[[redirects]]
  from = "https://nuxt-ackee-docs.netlify.app/*"
  to = "https://ackee.nuxtjs.org/:splat"
  status = 301
  force = true
